name: Build e deploy projeto Quarkus para Azure Function App - avaliacoes-tc-4

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Ambiente de deploy'
        required: true
        default: 'dev_mateus'
        type: choice
        options:
          - dev_mateus

env:
  PACKAGE_DIRECTORY: '.' # diretório que contém pom.xml
  JAVA_VERSION: '21' # versão Java

jobs:
  build-and-deploy:
    environment: ${{ inputs.ambiente }}
    runs-on: windows-latest
    permissions:
      id-token: write # Isto é necessário para solicitar o JWT
      contents: read # Isto é necessário para actions/checkout

    steps:
      - name: 'Fazer checkout do GitHub Action'
        uses: actions/checkout@v6

      - name: Configurar Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
          cache: 'maven' # cache das dependências da aplicação

      - name: 'Restaurar Dependências do Projeto Usando Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package
          popd

      - name: Fazer login no Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: 'Executar Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{vars.AZURE_FUNCTIONAPP_NAME}}'
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true