name: Build e deploy projeto Quarkus para Azure Function App - avaliacoes-tc-4

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Ambiente de deploy'
        required: true
        default: 'dev-mateus'
        type: choice
        options:
          - dev-mateus

env:
  PACKAGE_DIRECTORY: '.' # diretório que contém pom.xml
  JAVA_VERSION: '21' # versão Java

jobs:
  build-and-deploy:
    environment: ${{ inputs.ambiente }}
    runs-on: windows-latest
    permissions:
      id-token: write # Isto é necessário para solicitar o JWT
      contents: read # Isto é necessário para actions/checkout

    env:
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_FUNCTION_APP_NAME: ${{ vars.AZURE_FUNCTION_APP_NAME }}

    steps:
      - name: 'Fazer checkout do GitHub Action'
        uses: actions/checkout@v6

      - name: Configurar Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven' # cache das dependências da aplicação

      - name: 'Restaurar Dependências do Projeto Usando Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          ./mvnw clean package -DskipTests
          popd

      - name: Fazer login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: 'Configurar variáveis de ambiente no Function App'
        run: |
          az functionapp config appsettings set `
            --name ${{ env.AZURE_FUNCTION_APP_NAME }} `
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} `
            --settings `
              DB_URL="${{ secrets.DB_URL }}" `
              DB_USER="${{ secrets.DB_USER }}" `
              DB_PASSWORD="${{ secrets.DB_PASSWORD }}" `
        shell: pwsh

      - name: 'Executar Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{ env.AZURE_FUNCTION_APP_NAME }}'
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}/target/azure-functions/${{ env.AZURE_FUNCTION_APP_NAME }}'
          respect-pom-xml: false